# 전처리: 원본 → 결과 (5개 각각) + 정규화 과정

데이터마다 **원본 → 전처리 결과**. 큰 원본은 상위 몇 행만 미리보기(전체 차원은 shape로 표시).
정규화가 실제 실행되는 **GSE142025는 정규화 전/후**도 표시.

In [1]:
import pandas as pd, os, gzip, glob
from io import StringIO
pd.set_option('display.max_columns',18)
OLD='../../data/processed'; RAW='../../data'; BASE='../01_preprocessing/bulk/output'
# 어레이 원본: 전체 행수는 세고, 미리보기는 상위 n행만 (빠르게)
def series_preview(g,n=8):
    with gzip.open(f'{OLD}/{g}_series_matrix.txt.gz','rt') as f:
        L=[next(f) for _ in range(200)]  # 헤더+앞부분만
    s=next(i for i,l in enumerate(L) if l.startswith('"ID_REF"'))
    prev=pd.read_csv(StringIO(''.join(L[s:s+1+n])),sep='\t',index_col=0)
    total=sum(1 for _ in gzip.open(f'{OLD}/{g}_series_matrix.txt.gz','rt'))-s-1
    return prev,total

## 1) GSE30529 (어레이 U133A_2)

In [2]:
prev,tot=series_preview('GSE30529'); print(f'원본 probe {tot} × 샘플 {prev.shape[1]} (미리보기 상위 8)'); prev

원본 probe 22278 × 샘플 22 (미리보기 상위 8)

,GSM757014,GSM757015,GSM757016,GSM757017,GSM757018,GSM757019,GSM757020,GSM757021,GSM757022,GSM757023,GSM757024,GSM757025,GSM757026,GSM757027,GSM757028,GSM757029,GSM757030,GSM757031,GSM757032,GSM757033,GSM757034,GSM757035
ID_REF,,,,,,,,,,,,,,,,,,,,,,
1007_s_at,0.155938,0.095946,0.401841,0.516814,0.396273,0.080572,0.001711,-0.001711,-0.070795,0.087316,-0.567708,0.150060,-0.278130,-0.755840,-0.336245,-0.215036,-0.224906,-0.181286,-0.037560,0.384506,0.523873,-0.206517
1053_at,0.236349,0.119733,0.081872,0.505905,0.557108,0.445695,0.020680,0.368912,-0.280901,-0.026292,0.388839,-0.201556,-0.204894,-0.273985,-0.143702,-0.065200,0.056003,-0.020680,0.324200,-0.037938,-0.330404,-0.062925
117_at,-0.155251,0.173947,-0.033306,-0.058939,-0.103658,-0.391593,-0.207297,-0.182498,0.033306,0.070001,0.094212,0.434981,0.041830,0.547018,-0.243624,0.104335,0.070219,0.242287,-0.042539,-0.066455,0.289591,-0.177835
121_at,0.090568,0.440096,0.225213,-0.315482,-0.208008,-0.035012,0.035012,-0.382234,0.529364,0.076385,-0.742138,-0.290631,0.113528,-0.581059,-0.104211,0.100040,-0.045023,0.127093,-0.200264,0.615591,0.262560,-0.259607
1255_g_at,0.010099,-0.279639,-0.221435,0.097297,0.196349,-0.146091,-0.179054,0.029917,-0.010099,-0.140041,0.321712,0.124752,-0.070210,0.350707,0.228684,-0.110322,-0.205647,-0.157106,0.131065,0.057927,0.250332,-0.067621
1294_at,-0.104819,0.650456,-0.014148,1.178083,1.098426,0.171862,0.323442,0.646452,-0.202382,-0.468832,-0.328356,-0.088606,0.349469,0.014148,-0.205066,-0.504269,-0.216575,-0.192882,-0.254504,0.045607,0.368639,0.181739
1316_at,-0.247418,0.018172,-0.538636,-0.359284,-0.113217,-0.371768,-0.288343,-0.534824,0.062718,-0.562131,-0.018172,0.296373,0.972024,0.422305,0.079744,0.062660,0.448702,-0.126822,0.229161,0.091637,0.389339,-0.189566
1320_at,-0.068738,0.069029,-0.197250,0.477878,0.059189,-0.139506,-0.149893,0.002468,-0.229039,-0.207627,-0.058392,0.485013,0.011314,0.590702,0.122868,-0.105792,0.065138,-0.035649,-0.002468,0.056711,0.452045,-0.204400

In [3]:
df=pd.read_csv(f'{BASE}/01_genematrix/GSE30529.genematrix.txt',sep='\t',index_col=0)
print('결과 유전자×샘플:',df.shape,'(probe→유전자, RMA=log2+정규화 완료)'); df.head(8)

결과 유전자×샘플: (13041, 22) (probe→유전자, RMA=log2+정규화 완료)

,GSM757014,GSM757015,GSM757016,GSM757017,GSM757018,GSM757019,GSM757020,GSM757021,GSM757022,GSM757023,GSM757024,GSM757025,GSM757026,GSM757027,GSM757028,GSM757029,GSM757030,GSM757031,GSM757032,GSM757033,GSM757034,GSM757035
geneNames,,,,,,,,,,,,,,,,,,,,,,
DDR1,8.929265,9.193855,9.363028,9.078851,8.680475,9.517727,9.575387,8.844974,8.869273,8.975050,8.606721,8.980383,8.188301,8.138443,8.515825,8.625342,8.789590,8.716740,8.875076,8.969370,9.130896,8.450748
RFC2,5.655333,5.906418,5.581702,5.608812,5.207027,6.108938,5.919318,5.583715,5.858148,5.419599,5.536191,5.410445,5.612177,5.486258,5.464176,5.402843,5.586277,5.510320,5.694804,5.518068,5.276704,5.509828
HSPA6,5.702964,5.901149,5.408531,5.446837,5.700388,5.923768,5.110084,5.304455,5.561724,5.894353,5.540568,5.901360,5.579810,5.719324,5.453487,5.566866,5.581738,5.474117,5.530939,5.504949,5.593586,5.304748
PAX8,7.657273,6.882328,7.113481,7.172935,7.312945,7.276220,7.239304,7.252503,7.116980,6.972085,7.199040,7.135549,6.954461,7.356938,7.142401,6.902818,7.252822,7.075873,7.071901,7.544070,7.338060,7.068954
GUCA1A,4.389246,4.376325,4.395794,4.432834,4.356657,4.544146,4.307366,4.234587,4.521387,4.143261,4.421154,4.724654,4.755385,5.395768,4.788713,4.459762,4.528395,4.523623,4.559296,4.523059,4.587991,4.283534
UBA7,7.324307,7.844049,6.782658,6.589270,6.316348,7.915023,6.958384,7.007764,7.492082,6.189960,7.008023,6.610145,6.227453,6.425271,6.432829,6.127948,6.215723,6.433338,6.195764,6.681087,6.989184,6.828100
THRA,6.053758,5.872051,5.839461,5.823391,6.094934,5.939775,5.614258,5.852665,5.900080,5.522004,6.415010,6.409235,6.107442,6.328810,6.182048,6.100592,6.241648,6.083421,6.127586,6.262726,6.625513,6.178049
PTPN21,5.066210,5.393341,4.994323,5.113796,4.970333,5.131974,4.993096,4.974710,5.190715,4.945963,4.996750,5.347995,4.974736,5.515887,5.331474,4.997432,5.348320,5.024400,4.839889,5.039525,5.587637,4.937316

## 2) GSE96804 (어레이 HTA-2.0)

In [4]:
prev,tot=series_preview('GSE96804'); print(f'원본 probe {tot} × 샘플 {prev.shape[1]} (미리보기 상위 8)'); prev

원본 probe 70524 × 샘플 61 (미리보기 상위 8)

,GSM2544275,GSM2544276,GSM2544277,GSM2544278,GSM2544279,GSM2544280,GSM2544281,GSM2544282,GSM2544283,GSM2544284,GSM2544285,GSM2544286,GSM2544287,GSM2544288,GSM2544289,GSM2544290,GSM2544291,GSM2544292,GSM2544293,GSM2544294,GSM2544295,GSM2544296,GSM2544297,GSM2544298,GSM2544299,GSM2544300,GSM2544301,GSM2544302,GSM2544303,GSM2544304,GSM2544305,GSM2544306,GSM2544307,GSM2544308,GSM2544309,GSM2544310,GSM2544311,GSM2544312,GSM2544313,GSM2544314,GSM2544315,GSM2544316,GSM2544317,GSM2544318,GSM2544319,GSM2544320,GSM2544321,GSM2544322,GSM2544323,GSM2544324,GSM2544325,GSM2544326,GSM2544327,GSM2544328,GSM2544329,GSM2544330,GSM2544331,GSM2544332,GSM2544333,GSM2544334,GSM2544335
ID_REF,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2824546_st,17.5896,17.5399,17.9409,18.0654,17.2344,17.2888,17.6294,17.7115,17.8161,17.6692,17.4921,17.7446,17.1496,18.0722,17.2063,17.5504,17.6991,17.8163,18.4272,17.5884,17.7148,17.6844,17.5232,17.5517,17.5184,17.6759,17.7347,17.9758,17.1937,18.0307,17.5021,17.8758,18.0403,17.9981,18.1545,17.5634,18.0097,18.0045,17.7040,18.3620,17.4014,17.4431,17.2704,17.3706,17.1752,17.3925,17.6391,17.9380,17.7574,17.5817,17.2591,17.0642,17.2001,17.3797,17.4557,17.3103,18.0813,16.9303,17.8172,18.2423,17.6159
2824549_st,18.2517,18.1919,17.7355,18.4033,18.2757,18.0327,18.0726,18.2135,17.8432,18.0058,18.1443,17.8253,17.9741,17.9119,18.6383,18.0909,17.9905,17.5483,18.8402,18.0056,17.8517,18.8870,18.2966,18.7069,18.1035,18.4679,18.9345,18.4034,17.9647,18.4871,17.9058,18.5504,17.7463,18.0274,18.3993,18.4749,18.7954,18.3077,18.2062,18.5433,18.1567,17.8180,17.9495,17.7578,17.6848,18.0336,18.0109,18.2987,17.9156,17.7843,17.6877,17.6026,17.8938,17.9758,18.1244,17.8440,18.6880,17.5904,18.5222,18.3010,18.2511
2824551_st,17.2263,18.4739,18.2130,18.6644,18.2393,18.0013,17.9779,17.9213,18.0886,18.7621,18.2756,17.8931,18.3778,18.3920,17.7770,18.4792,18.1221,18.0084,18.5017,17.5844,18.3856,18.1692,17.9997,18.6428,18.2717,18.7804,18.2622,18.7357,17.7772,18.7275,18.5034,18.8230,18.0593,18.4445,18.5515,18.0749,18.6783,18.7815,18.2799,18.5654,17.6986,18.1310,18.4742,18.2791,18.5942,17.9704,18.5090,18.4017,18.0183,18.4146,18.5422,18.1088,18.1757,18.4493,18.1076,18.1546,18.7345,17.8711,18.3212,18.8156,18.8209
2824554_st,19.0005,19.4484,18.9198,19.2666,19.0124,19.0052,18.9649,19.3083,19.1233,19.4347,19.2276,19.1191,19.0744,19.0206,18.9622,19.2329,19.3448,19.0407,18.9948,19.1140,19.0294,19.2094,19.0615,18.8035,19.0199,19.4457,18.8901,19.3841,18.2380,19.2950,19.5360,19.0502,18.9191,19.1229,19.3273,18.8417,19.4443,19.0889,19.1317,18.9204,18.9476,18.7275,19.0880,19.0494,19.3228,19.1592,18.9502,19.0816,19.0845,18.7020,18.9582,18.8585,19.0843,19.2117,19.0169,19.1155,19.1507,18.6324,19.1315,19.1419,19.1399
2827992_st,18.7149,19.5708,19.1092,19.1364,18.3277,18.7405,19.2299,19.5907,18.5446,19.0625,18.9420,18.8857,18.2553,19.5291,18.4734,19.0472,19.4781,18.3096,18.8163,19.0897,19.5500,19.5156,19.1666,19.0234,19.1535,19.3622,19.7129,19.5541,18.6635,19.4508,19.1985,19.3942,19.4239,19.5416,19.8166,18.7441,19.5144,19.3375,19.2665,19.1447,18.8696,19.0795,19.2263,19.0293,19.0259,19.1587,18.7204,19.3241,19.5841,19.3363,19.4132,19.5346,19.8166,19.4694,19.2812,18.8527,19.6083,19.4033,19.4918,19.1222,18.8476
2827995_st,19.0952,19.6297,19.7445,19.1198,18.9458,19.1028,19.3412,19.5406,19.1048,19.3406,19.5251,19.0036,18.3965,19.4535,18.1671,19.3708,19.6170,18.9978,19.1840,18.8323,19.9016,19.8229,19.4282,19.0242,19.1026,19.5152,19.0644,19.5073,19.1388,19.9016,19.8478,19.0678,19.3336,19.8747,19.8166,19.8290,19.4991,19.6564,19.5906,19.8023,18.7560,18.9753,18.6073,19.5156,19.7122,18.9474,19.4672,19.2944,19.6647,19.6582,19.7828,19.5510,19.8166,19.4626,19.4823,19.2410,19.4991,19.1039,19.4480,19.5376,19.4221
2827996_st,18.6905,19.2866,19.0675,18.9145,18.9724,18.8844,18.8789,19.5801,18.9967,19.1834,19.1793,19.0596,18.6344,18.7490,18.2357,19.3247,19.2374,18.9747,19.1104,19.1542,19.3265,19.4492,18.5541,19.0567,18.7799,18.9370,19.2559,19.4508,18.8300,19.7592,19.5474,19.6108,19.2547,19.3986,19.5050,19.0240,19.6760,18.9049,19.5843,19.1137,18.9547,18.8003,18.4201,19.0606,19.0036,19.1430,18.9248,19.1562,19.0309,18.9144,19.0796,18.6867,18.4471,19.1329,19.4501,18.8128,19.2633,18.7114,19.1637,18.7926,18.6297
2828010_st,14.7191,15.7093,16.1834,16.1001,15.6647,14.8844,14.7442,15.5866,14.5906,16.3021,15.2802,15.2997,15.6142,16.2993,14.8387,15.5406,15.7332,15.1271,15.1283,14.6421,16.1361,15.9211,15.7985,15.8715,14.9174,15.5531,15.0756,16.2883,14.2094,15.7595,16.1081,15.9705,15.9165,16.0053,15.1821,15.1792,15.2532,16.1497,15.9473,15.5997,15.1871,15.1069,15.1536,15.2050,15.8289,15.5643,15.0229,15.6456,15.7166,15.3435,15.7478,15.8176,16.0509,15.4545,15.3427,15.6187,16.7391,14.9750,16.2453,16.1072,14.9339

In [5]:
df=pd.read_csv(f'{BASE}/01_genematrix/GSE96804.genematrix.txt',sep='\t',index_col=0)
print('결과 유전자×샘플:',df.shape,'(probe 70,523→유전자 23,910, 비유전자 제외)'); df.head(8)

결과 유전자×샘플: (23910, 61) (probe 70,523→유전자 23,910, 비유전자 제외)

,GSM2544275,GSM2544276,GSM2544277,GSM2544278,GSM2544279,GSM2544280,GSM2544281,GSM2544282,GSM2544283,GSM2544284,GSM2544285,GSM2544286,GSM2544287,GSM2544288,GSM2544289,GSM2544290,GSM2544291,GSM2544292,GSM2544293,GSM2544294,GSM2544295,GSM2544296,GSM2544297,GSM2544298,GSM2544299,GSM2544300,GSM2544301,GSM2544302,GSM2544303,GSM2544304,GSM2544305,GSM2544306,GSM2544307,GSM2544308,GSM2544309,GSM2544310,GSM2544311,GSM2544312,GSM2544313,GSM2544314,GSM2544315,GSM2544316,GSM2544317,GSM2544318,GSM2544319,GSM2544320,GSM2544321,GSM2544322,GSM2544323,GSM2544324,GSM2544325,GSM2544326,GSM2544327,GSM2544328,GSM2544329,GSM2544330,GSM2544331,GSM2544332,GSM2544333,GSM2544334,GSM2544335
geneNames,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
DDX11L1,5.449793,5.309529,5.731438,4.942954,5.137041,5.223526,5.283020,5.097324,5.200696,5.272083,5.522070,5.213495,5.719367,4.996224,5.228170,5.285046,6.149575,5.388088,5.130602,5.130170,4.878793,5.756840,5.002266,5.387309,5.774045,5.050359,5.206583,5.248526,5.472235,5.473197,5.047082,5.645363,5.224864,4.959216,4.892866,5.782782,5.478453,4.918820,5.285026,5.463953,5.480335,4.952928,5.254245,5.152358,5.257515,4.965628,5.195029,5.480117,5.023414,5.069536,5.200328,5.282321,5.248273,5.363817,4.743726,5.066017,5.486663,5.460603,5.357311,4.749867,5.478413
OR4F5,2.614881,2.895032,2.677335,2.694385,2.659347,2.610405,2.821303,2.655156,2.803923,2.684462,2.575239,2.586201,3.009006,2.458724,2.963678,2.706206,2.517391,2.481136,2.639507,2.954173,2.941072,3.080107,2.373583,2.731954,2.879217,2.581599,3.078698,2.535832,2.651941,2.871095,3.031955,2.861202,2.680448,2.799872,3.044062,2.963649,2.883760,2.669944,2.961752,3.462270,2.552021,2.677189,2.895674,2.872428,2.795499,2.756245,2.664834,2.844734,2.727122,2.819239,2.851542,2.691636,3.086809,2.785781,3.107920,2.730735,3.222024,2.592836,2.777122,2.869830,3.014041
LINC01001,7.923709,7.854996,7.805248,7.581241,8.032891,7.898711,7.511582,7.957225,8.022925,7.434613,8.417606,8.033885,7.705230,7.642196,7.630694,7.866497,7.482730,7.868219,7.465379,8.197586,7.899912,8.030741,7.898754,7.399011,7.995936,7.279429,7.561188,7.828236,7.689591,8.066617,8.228488,7.303196,7.959765,8.208111,7.767799,7.710796,7.756276,7.851211,8.199513,7.766971,7.521388,7.713923,7.517916,7.474995,7.974332,7.703185,7.836013,7.418596,7.373620,7.166983,7.395122,7.643354,7.805440,7.399532,7.468427,7.609446,7.834734,7.540132,7.856660,7.562755,8.031527
LINC01061,8.581674,8.229818,8.379002,7.903429,8.476581,8.489779,8.373113,8.628292,8.685747,8.235995,9.073397,8.546813,8.168779,8.226965,8.058779,8.521475,8.227465,8.623358,7.741895,8.658991,8.549521,8.611310,8.462604,8.030473,8.519863,8.166678,8.300806,8.530826,8.486726,9.050158,9.071523,8.079365,8.644084,8.818110,8.483251,8.477106,8.425936,8.438130,8.711943,8.418561,8.184511,8.344328,8.104786,8.094724,8.607148,8.271498,8.331318,7.964878,7.969601,7.885102,7.943358,8.164665,8.412470,8.078325,7.789780,8.217921,8.310882,8.166327,8.535288,7.964805,8.495713
OR4F29,2.521754,2.978591,2.511679,2.485194,2.621120,2.546207,2.455206,2.473575,2.596680,2.501765,2.501859,2.507207,2.447755,2.638326,2.550693,2.510034,2.661669,2.718617,2.923691,2.740020,2.844308,2.682149,2.743995,2.600994,2.676176,2.623482,2.507493,2.464157,2.892018,2.530522,2.831838,2.679697,2.397401,2.589811,2.960572,2.715319,3.370404,2.628531,2.814878,2.931014,2.765018,2.646267,2.916092,2.690961,2.641551,2.882180,2.520822,2.473887,2.719336,2.870650,2.539531,2.515116,2.781767,2.544799,2.766426,2.639104,2.585350,2.728235,2.655763,2.570610,2.594803
LOC101928626,2.544273,2.803776,2.965910,2.945302,2.903176,2.782755,3.086363,2.601176,2.655026,2.877368,2.587783,2.841954,2.804564,2.436897,2.995191,2.598641,2.564760,2.749024,2.962551,3.506720,2.755662,3.091233,2.749733,2.903978,3.035642,2.754072,2.653800,2.482622,3.040755,2.698450,2.722808,2.679324,2.526516,2.624887,3.109567,2.775152,2.824242,2.781031,3.045451,3.142152,2.689954,3.155208,2.825019,2.872062,2.637070,2.584505,2.558829,2.590512,2.771353,2.825150,3.079154,2.807020,3.093775,2.979588,2.737743,2.817991,2.676133,2.851138,2.603226,3.000624,2.795980
LINC01128,6.216794,6.208103,6.453607,6.177190,6.362112,6.360751,6.432639,6.263518,6.486097,6.238265,6.469620,6.585735,6.067372,6.234954,6.586206,6.267733,6.257200,6.370693,6.216902,6.437025,5.978928,6.282985,6.268583,6.345539,6.434981,6.136482,6.311615,6.167579,6.360704,6.264341,6.273202,6.232880,6.119749,6.493878,5.825392,6.331450,6.413837,6.301272,6.451954,6.218247,6.163421,6.329467,6.201188,6.128154,6.377805,6.024192,6.217252,6.279846,6.268717,6.076686,6.281260,5.936106,6.079729,6.119180,6.309756,6.208329,6.543895,6.115021,6.452771,6.323909,6.368304
LOC284600,6.276993,6.013615,6.473978,6.283703,6.329139,6.367874,6.359638,6.429768,6.483762,6.262616,6.369247,6.558988,6.410526,6.399746,6.420742,5.965154,6.313331,6.301267,6.379327,6.419865,6.303511,6.292148,6.245140,6.108238,6.432644,6.183736,6.134369,6.338626,6.278647,6.149920,6.278686,6.518614,6.463224,6.520079,6.308418,6.548372,6.437989,6.383476,6.567403,6.378571,6.325286,6.124168,6.101018,6.273483,6.444078,6.204773,6.011794,6.075770,6.009030,6.205183,6.322714,6.291813,6.578466,6.480672,6.234096,6.287652,6.182439,6.007765,6.374839,6.176442,6.164561

## 3) GSE104948 (U133A+Plus2 혼합) — 원본 CEL 샘플목록

In [6]:
df_raw=pd.read_csv('../01_preprocessing/bulk/GSE104948_chipmap.csv')
print('CEL 196개 중 사용:',df_raw.shape[0],'(DN=DKD/LD=Control, 칩 712·1164)'); df_raw

CEL 196개 중 사용: 33 (DN=DKD/LD=Control, 칩 712·1164)

                                file         gsm    group  chip
0      GSM2810645_H1-Glom-DN1.CEL.gz  GSM2810645      DKD   712
1     GSM2810646_H1-Glom-DN10.CEL.gz  GSM2810646      DKD   712
2      GSM2810647_H1-Glom-DN2.CEL.gz  GSM2810647      DKD   712
3      GSM2810648_H1-Glom-DN5.CEL.gz  GSM2810648      DKD   712
4      GSM2810649_H1-Glom-DN8.CEL.gz  GSM2810649      DKD   712
5   GSM2810714_H5-Glom-LD_478.CEL.gz  GSM2810714  Control   712
6   GSM2810715_H5-Glom-LD_479.CEL.gz  GSM2810715  Control   712
7   GSM2810716_H5-Glom-LD_482.CEL.gz  GSM2810716  Control   712
8    GSM2810770_H7-Glom-DN901.CEL.gz  GSM2810770      DKD  1164
9    GSM2810771_H7-Glom-DN910.CEL.gz  GSM2810771      DKD  1164
10   GSM2810772_H7-Glom-DN914.CEL.gz  GSM2810772      DKD  1164
11   GSM2810773_H7-Glom-DN916.CEL.gz  GSM2810773      DKD  1164
12   GSM2810774_H7-Glom-DN932.CEL.gz  GSM2810774      DKD  1164
13   GSM2810775_H7-Glom-DN941.CEL.gz  GSM2810775      DKD  1164
14   GSM2810776_H7-Glom-DN947.CEL.gz  GSM2810776      DKD  1164
15  GSM2810793_H7-Glom-LD_974.CEL.gz  GSM2810793  Control  1164
16  GSM2810794_H7-Glom-LD_975.CEL.gz  GSM2810794  Control  1164
17  GSM2810795_H7-Glom-LD_976.CEL.gz  GSM2810795  Control  1164
18  GSM2810796_H7-Glom-LD_978.CEL.gz  GSM2810796  Control  1164
19  GSM2810797_H7-Glom-LD_979.CEL.gz  GSM2810797  Control  1164
20  GSM2810798_H7-Glom-LD_980.CEL.gz  GSM2810798  Control  1164
21  GSM2810799_H7-Glom-LD_981.CEL.gz  GSM2810799  Control  1164
22  GSM2810800_H7-Glom-LD_982.CEL.gz  GSM2810800  Control  1164
23  GSM2810801_H7-Glom-LD_983.CEL.gz  GSM2810801  Control  1164
24  GSM2810802_H7-Glom-LD_984.CEL.gz  GSM2810802  Control  1164
25  GSM2810803_H7-Glom-LD_985.CEL.gz  GSM2810803  Control  1164
26  GSM2810804_H7-Glom-LD_987.CEL.gz  GSM2810804  Control  1164
27  GSM2810805_H7-Glom-LD_988.CEL.gz  GSM2810805  Control  1164
28  GSM2810806_H7-Glom-LD_989.CEL.gz  GSM2810806  Control  1164
29  GSM2810807_H7-Glom-LD_990.CEL.gz  GSM2810807  Control  1164
30  GSM2810808_H7-Glom-LD_992.CEL.gz  GSM2810808  Control  1164
31  GSM2810809_H7-Glom-LD_993.CEL.gz  GSM2810809  Control  1164
32  GSM2810810_H7-Glom-LD_994.CEL.gz  GSM2810810  Control  1164

In [7]:
df=pd.read_csv(f'{BASE}/01_genematrix/GSE104948.genematrix.txt',sep='\t',index_col=0)
print('결과 유전자×샘플:',df.shape,'(칩2종 각각 RMA→병합)'); df.head(8)

결과 유전자×샘플: (12042, 33) (칩2종 각각 RMA→병합)

,GSM2810770,GSM2810771,GSM2810772,GSM2810773,GSM2810774,GSM2810775,GSM2810776,GSM2810793,GSM2810794,GSM2810795,GSM2810796,GSM2810797,GSM2810798,GSM2810799,GSM2810800,GSM2810801,GSM2810802,GSM2810803,GSM2810804,GSM2810805,GSM2810806,GSM2810807,GSM2810808,GSM2810809,GSM2810810,GSM2810645,GSM2810646,GSM2810647,GSM2810648,GSM2810649,GSM2810714,GSM2810715,GSM2810716
geneNames,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
NAT2,7.623965,7.220714,6.235703,6.543869,6.388772,6.805480,6.616893,6.875469,6.566198,6.678173,6.311362,6.475945,6.054280,6.732769,5.994602,6.357684,6.566198,6.664092,6.415218,6.414600,6.566198,5.969913,6.907160,6.835877,6.603590,6.396783,6.018791,5.851502,6.223035,5.837872,5.732965,5.443767,5.849508
ADA,7.108499,7.005805,6.893924,7.231034,6.848429,7.164193,6.770608,5.920232,5.641223,5.739122,6.018483,5.876107,5.543797,5.873949,6.042307,5.850204,6.158636,6.127766,6.031811,5.887742,5.728360,5.861500,5.806059,5.899702,5.684190,5.683875,6.119733,5.659696,5.928811,7.219128,5.436554,5.501970,5.419793
CDH2,8.159382,8.506378,7.468009,8.125018,9.598557,8.057861,8.168386,8.025833,8.082519,8.040603,7.859944,7.701388,7.804291,7.166034,7.919354,7.175504,7.656073,7.752563,7.590201,7.227583,8.101756,7.100620,8.177280,7.506346,7.501610,5.458797,6.357445,5.965731,5.439957,5.700852,5.870565,5.646901,5.692473
AKT3,7.506402,7.357146,7.971828,7.363836,7.224928,7.596838,7.327433,7.605915,7.614536,7.448635,7.549123,7.404560,7.569183,7.513073,7.658872,7.523875,7.677009,7.671216,7.473397,7.811161,7.075183,7.814854,7.292927,7.567902,7.500355,8.574079,8.296454,8.748320,8.321241,8.484327,8.594472,8.538571,8.521033
MED6,7.342756,7.464278,7.622829,7.085060,7.428092,7.225361,7.135654,6.968016,7.379390,7.026124,7.203944,7.053996,6.951435,6.921118,7.002404,6.555712,6.972268,6.891766,6.981183,6.861158,6.992855,7.214060,6.864620,6.748594,7.085060,4.239778,4.133908,4.070605,4.061528,4.125855,4.619603,4.633620,4.705598
NR2E3,4.599194,4.586195,4.420645,4.825586,4.383010,4.444030,4.478816,4.663201,4.618338,4.728508,4.638844,4.564273,4.670443,4.670842,4.629190,4.973407,4.617252,4.679930,4.656000,4.596423,4.749617,4.647025,4.540433,4.543219,4.615883,4.420255,4.360100,4.448886,4.989641,4.611507,4.419060,4.414810,4.567831
NAALAD2,4.953113,5.273439,5.044016,4.784050,4.819031,4.827582,5.326012,4.738450,5.091576,4.510064,4.529576,5.301201,5.077214,5.044684,4.488549,4.744251,4.645474,5.068441,4.816693,4.598884,4.816693,5.802573,5.374525,5.000850,4.753230,3.966607,3.851913,3.957602,3.721696,3.835735,3.690289,3.866738,3.612007
NAALADL1,6.789260,6.448473,7.074546,7.132775,6.118119,6.771711,6.554265,7.030964,6.833635,6.620653,6.966028,6.589123,6.436900,6.935461,6.966614,7.115718,6.503376,6.450822,6.959048,6.785944,6.756084,6.756084,6.417745,6.655252,6.474082,5.010058,4.797885,5.044552,5.300899,4.771770,5.066530,5.080820,5.470879

## 4) GSE104954 (U133A+Plus2 혼합)

In [8]:
df_raw=pd.read_csv('../01_preprocessing/bulk/GSE104954_chipmap.csv')
print('CEL 195개 중 사용:',df_raw.shape[0]); df_raw

CEL 195개 중 사용: 38

                               file         gsm    group  chip
0      GSM2810894_H1-Tub-DN1.CEL.gz  GSM2810894      DKD   712
1     GSM2810895_H1-Tub-DN10.CEL.gz  GSM2810895      DKD   712
2     GSM2810896_H1-Tub-DN11.CEL.gz  GSM2810896      DKD   712
3      GSM2810897_H1-Tub-DN2.CEL.gz  GSM2810897      DKD   712
4      GSM2810898_H1-Tub-DN3.CEL.gz  GSM2810898      DKD   712
5      GSM2810899_H1-Tub-DN5.CEL.gz  GSM2810899      DKD   712
6      GSM2810900_H1-Tub-DN6.CEL.gz  GSM2810900      DKD   712
7      GSM2810901_H1-Tub-DN7.CEL.gz  GSM2810901      DKD   712
8      GSM2810902_H1-Tub-DN8.CEL.gz  GSM2810902      DKD   712
9      GSM2810903_H1-Tub-DN9.CEL.gz  GSM2810903      DKD   712
10   GSM2811026_H5-Tub-LD373.CEL.gz  GSM2811026  Control   712
11   GSM2811027_H5-Tub-LD374.CEL.gz  GSM2811027  Control   712
12   GSM2811028_H5-Tub-LD375.CEL.gz  GSM2811028  Control   712
13  GSM2811029_H7-Tub-DN1101.CEL.gz  GSM2811029      DKD  1164
14  GSM2811030_H7-Tub-DN1108.CEL.gz  GSM2811030      DKD  1164
15  GSM2811031_H7-Tub-DN1110.CEL.gz  GSM2811031      DKD  1164
16  GSM2811032_H7-Tub-DN1114.CEL.gz  GSM2811032      DKD  1164
17  GSM2811033_H7-Tub-DN1132.CEL.gz  GSM2811033      DKD  1164
18  GSM2811034_H7-Tub-DN1133.CEL.gz  GSM2811034      DKD  1164
19  GSM2811035_H7-Tub-DN1139.CEL.gz  GSM2811035      DKD  1164
20  GSM2811043_H7-Tub-LD1164.CEL.gz  GSM2811043  Control  1164
21  GSM2811044_H7-Tub-LD1165.CEL.gz  GSM2811044  Control  1164
22  GSM2811045_H7-Tub-LD1166.CEL.gz  GSM2811045  Control  1164
23  GSM2811046_H7-Tub-LD1168.CEL.gz  GSM2811046  Control  1164
24  GSM2811047_H7-Tub-LD1169.CEL.gz  GSM2811047  Control  1164
25  GSM2811048_H7-Tub-LD1170.CEL.gz  GSM2811048  Control  1164
26  GSM2811049_H7-Tub-LD1171.CEL.gz  GSM2811049  Control  1164
27  GSM2811050_H7-Tub-LD1172.CEL.gz  GSM2811050  Control  1164
28  GSM2811051_H7-Tub-LD1173.CEL.gz  GSM2811051  Control  1164
29  GSM2811052_H7-Tub-LD1174.CEL.gz  GSM2811052  Control  1164
30  GSM2811053_H7-Tub-LD1175.CEL.gz  GSM2811053  Control  1164
31  GSM2811054_H7-Tub-LD1177.CEL.gz  GSM2811054  Control  1164
32  GSM2811055_H7-Tub-LD1178.CEL.gz  GSM2811055  Control  1164
33  GSM2811056_H7-Tub-LD1179.CEL.gz  GSM2811056  Control  1164
34  GSM2811057_H7-Tub-LD1180.CEL.gz  GSM2811057  Control  1164
35  GSM2811058_H7-Tub-LD1182.CEL.gz  GSM2811058  Control  1164
36  GSM2811059_H7-Tub-LD1183.CEL.gz  GSM2811059  Control  1164
37  GSM2811060_H7-Tub-LD1184.CEL.gz  GSM2811060  Control  1164

In [9]:
df=pd.read_csv(f'{BASE}/01_genematrix/GSE104954.genematrix.txt',sep='\t',index_col=0)
print('결과 유전자×샘플:',df.shape); df.head(8)

결과 유전자×샘플: (12042, 38)

,GSM2811029,GSM2811030,GSM2811031,GSM2811032,GSM2811033,GSM2811034,GSM2811035,GSM2811043,GSM2811044,GSM2811045,GSM2811046,GSM2811047,GSM2811048,GSM2811049,GSM2811050,GSM2811051,GSM2811052,GSM2811053,GSM2811054,GSM2811055,GSM2811056,GSM2811057,GSM2811058,GSM2811059,GSM2811060,GSM2810894,GSM2810895,GSM2810896,GSM2810897,GSM2810898,GSM2810899,GSM2810900,GSM2810901,GSM2810902,GSM2810903,GSM2811026,GSM2811027,GSM2811028
geneNames,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
NAT2,5.419746,5.743840,5.360361,5.223338,6.197162,5.465758,5.050059,5.788488,5.066701,5.531461,5.169579,5.157530,5.117352,5.179331,5.213161,4.801603,5.642884,5.235320,5.242060,5.824169,5.299821,5.735124,5.052858,5.598924,5.369249,5.818328,5.820831,5.748189,6.324428,5.848265,6.162858,5.891786,6.233065,6.196238,5.757940,5.406214,5.523262,5.145980
ADA,4.814271,4.477460,5.434096,4.681333,4.751843,4.535291,5.109590,4.761168,4.578959,4.474278,4.376758,4.543823,4.564169,4.487392,4.348672,4.401477,4.528494,4.848796,4.672803,4.496855,4.488859,4.695894,4.300921,4.530274,4.515984,4.947358,5.165209,5.002204,5.076499,5.327508,5.135764,5.388783,5.240093,5.588868,5.395967,5.038926,4.798886,4.953628
CDH2,8.486684,8.467889,7.907876,8.303119,8.153896,8.163600,7.803034,7.852424,8.052181,8.084313,8.287222,8.107848,8.142121,7.773980,8.030964,7.987134,8.233236,8.091361,8.270546,8.197253,7.756712,8.240902,8.246533,8.042440,7.948477,6.839778,7.041170,6.825626,6.548688,6.527823,6.741689,6.734941,6.718739,6.766771,5.979890,6.649185,6.922357,6.740601
AKT3,5.330302,5.126612,5.395509,5.184315,5.300981,5.300981,5.449464,5.040661,5.357819,5.255400,5.181322,5.118308,5.178602,5.163084,5.429263,4.963298,5.264915,5.218929,5.184315,5.120772,5.040216,5.179009,4.940802,5.151465,5.215772,5.686664,5.917167,5.863891,5.994185,6.081604,5.964556,6.152565,5.813741,5.842454,5.938153,5.739139,5.689646,5.514841
MED6,6.890379,6.285632,6.403384,6.268087,5.883815,5.989446,6.799601,5.191392,6.476605,6.374591,6.302578,6.376616,6.232621,6.226317,6.290231,5.835285,6.565142,6.231635,5.998901,6.225951,5.941869,6.254664,6.451843,6.208598,6.459082,4.395575,4.231042,4.299202,4.276059,4.438043,4.396134,4.332248,4.154986,4.354096,4.380600,4.793138,4.576609,4.481277
NR2E3,3.595447,3.669068,3.903672,3.772775,4.059785,3.721251,3.959164,4.198349,3.499861,3.958666,3.746294,3.599679,3.717835,3.639945,3.753366,3.564713,3.803637,3.911272,3.853338,3.771399,3.744290,3.655320,3.549080,3.682606,3.725815,4.105869,4.193003,4.185572,4.065714,4.009565,4.105507,4.162481,4.252304,4.391809,4.403211,4.109691,4.065976,4.043331
NAALAD2,3.141574,2.937313,3.825627,3.194696,3.066191,3.372851,3.453964,3.328212,3.276922,3.084666,3.135333,3.098115,3.369950,3.269219,3.280740,3.432262,3.237139,3.719456,3.211185,3.128054,3.322566,3.796102,3.153455,3.171761,3.242824,3.416070,3.361231,3.321929,3.371431,3.461205,3.415386,3.378672,3.360064,3.314298,3.649520,3.379197,3.507279,3.353661
NAALADL1,5.067029,4.912205,5.498667,5.053837,5.306767,5.340348,5.154660,5.823693,5.334178,5.069832,5.076563,4.944463,5.169645,5.039522,5.145787,5.009152,5.076448,5.610687,5.185922,5.223026,5.450956,5.057948,5.315500,5.025704,4.988914,4.029754,4.237630,4.155379,4.277342,4.072810,4.143733,4.258002,4.360050,4.356850,4.327187,3.957837,3.987263,3.911152

## 5) GSE142025 (RNA-seq) — 원본부터 심볼

In [10]:
fs=sorted(glob.glob(f'{RAW}/1-4. GSE142025_RAW/*.txt.gz'))
df_raw=pd.read_csv(fs[0],sep='\t'); print(f'원본 파일 {len(fs)}개, 각 심볼×값:',df_raw.shape); df_raw.head(8)

원본 파일 36개, 각 심볼×값: (17184, 2)

     Symbol       A11A
0      A1BG   6.866819
1  A1BG-AS1   5.569898
2      A1CF  10.919599
3       A2M  16.263047
4   A2M-AS1   8.006878
5    A4GALT  11.661596
6     A4GNT   6.695364
7      AAAS  10.665679

In [11]:
df=pd.read_csv(f'{BASE}/01_genematrix/GSE142025.genematrix.txt',sep='\t',index_col=0)
print('병합 결과 유전자×샘플:',df.shape); df.head(8)

병합 결과 유전자×샘플: (17184, 36)

,A11A,A12A,A13A,A14A,A15A,A17A,A18A,A19A,A20A,A21A,A22A,A23A,A24A,A25A,A26A,A28A,A29A,A30A,A31A,A32A,A33A,B3B,B4B,B5B,B6B,B8B,B9B,N2A,N3A,N5B,N6B,N7B,N8B,N10B,N12B,N13B
geneNames,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
A1BG,6.866819,6.947427,6.824098,7.386014,7.428343,7.168584,7.917317,7.725042,7.419004,6.785917,6.940540,6.736050,7.717509,7.133951,7.736946,6.914328,6.119405,7.355977,7.246352,7.072140,6.702656,6.392371,6.330405,6.820246,6.563131,7.050308,6.528168,6.469842,6.203464,6.888575,5.273028,6.417218,5.997890,6.623161,6.391958,5.697620
A1BG-AS1,5.569898,6.295194,5.738570,6.510046,6.930343,4.605649,7.436713,6.695364,6.227500,5.870013,6.391545,6.604291,5.885054,6.289514,6.895121,6.035207,5.929707,6.140356,6.845240,6.316558,5.510968,5.465347,6.173528,6.190452,5.977362,5.598883,6.029563,5.719696,5.456240,6.201278,4.484043,5.512423,5.159483,5.978862,5.478157,4.877218
A1CF,10.919599,11.271185,12.103053,11.525433,10.544823,10.869673,9.253155,10.306971,10.487491,11.288373,11.174769,11.997887,11.056253,11.383361,10.468693,10.683659,12.141484,11.385980,9.702990,11.854978,12.102831,11.956522,12.837708,12.267798,11.832790,11.953380,12.249015,12.185284,12.509666,12.130412,12.324429,12.568520,12.353611,12.398768,12.272683,12.245974
A2M,16.263047,16.355500,16.324612,16.485816,16.529039,15.626727,16.286824,16.263047,16.582387,16.136284,16.228550,16.010469,16.286824,16.760883,16.529039,17.281969,14.682377,16.286824,17.151443,16.286824,15.242800,15.229170,15.459651,15.301756,15.670659,15.055246,15.035374,15.475354,14.997607,15.376017,15.131920,15.008034,15.242800,15.607762,15.348862,15.091870
A2M-AS1,8.006878,7.350193,7.855322,8.051924,8.763796,7.867349,8.820032,8.474119,8.265362,7.680565,7.722889,7.939991,7.399227,8.191375,8.778039,8.367761,7.734992,7.820654,7.293855,7.696993,7.388275,7.556442,7.750161,7.119460,7.645756,7.556537,7.432906,7.450052,7.514131,7.281881,7.258395,7.532757,7.257831,7.753721,7.558049,7.302397
A4GALT,11.661596,11.672175,11.106141,11.104311,11.499382,11.937155,11.532014,11.519927,11.297063,11.738423,11.387692,11.300646,11.194402,11.475803,11.471783,11.069388,11.439888,11.309553,12.005243,11.476316,11.504378,11.529279,10.975482,11.599421,11.810890,11.339914,11.493189,11.161922,11.048622,11.169556,11.280299,11.190465,11.010524,12.099354,11.418056,11.279607
A4GNT,6.695364,7.259616,6.382167,7.511522,6.295194,6.104777,6.087031,5.770593,6.309013,8.242643,7.166322,7.867824,6.036842,6.842717,7.164266,6.098843,7.335629,5.037509,8.709646,7.292834,5.834351,7.486608,7.854311,7.132898,7.408723,5.974479,7.335502,7.300469,5.576221,7.185370,6.240355,6.234734,8.421187,6.261067,6.391958,7.216289
AAAS,10.665679,11.012944,10.977841,10.996060,10.870419,11.125723,10.832120,11.145322,10.931705,10.776207,10.969996,11.211907,11.111920,10.962027,10.935483,10.846324,11.213187,10.976836,10.638939,11.151351,11.078644,11.085078,11.074094,11.189964,11.010035,11.079864,11.065724,11.123314,10.900453,10.987988,11.013332,11.068786,11.061591,10.739304,10.892520,10.745793

## 정규화 과정 (GSE142025)
RNA-seq는 log2+정규화 실제 수행. **샘플별 평균**이 정규화 후 균일해짐.
(어레이는 RMA가 이미 정규화 → 스킵)

In [12]:
before=pd.read_csv(f'{BASE}/01_genematrix/GSE142025.genematrix.txt',sep='\t',index_col=0)
after =pd.read_csv(f'{BASE}/02_normalized/GSE142025.normalized.txt',sep='\t',index_col=0)
cmp=pd.DataFrame({'정규화 전 평균':before.mean().round(3).values[:8],
                  '정규화 후 평균':after.mean().round(3).values[:8]}, index=list(before.columns[:8]))
print('앞 8개 샘플 평균: 전은 들쭉날쭉 → 후는 균일'); cmp

앞 8개 샘플 평균: 전은 들쭉날쭉 → 후는 균일

      정규화 전 평균  정규화 후 평균
A11A     9.694     9.694
A12A     9.694     9.694
A13A     9.694     9.694
A14A     9.694     9.694
A15A     9.694     9.694
A17A     9.694     9.694
A18A     9.694     9.694
A19A     9.694     9.694

## 자동 대조 — 새 vs 기존

In [13]:
def gm(c): return {x.split('_')[0]:x for x in c}
rows=[]
for g in ['GSE30529','GSE96804','GSE104948','GSE104954','GSE142025']:
    n=pd.read_csv(f'{BASE}/01_genematrix/{g}.genematrix.txt',sep='\t',index_col=0)
    o=pd.read_csv(f'{OLD}/{g}.labeled.txt',sep='\t',index_col=0)
    nm,om=gm(n.columns),gm(o.columns); cm=sorted(set(nm)&set(om))
    ck=lambda x:('-' if (x not in n.index or x not in o.index or not cm) else ('O' if abs(n.loc[x,nm[cm[0]]]-o.loc[x,om[cm[0]]])<0.01 else 'X'))
    rows.append([g,f'{n.shape[0]}×{n.shape[1]}',f'{o.shape[0]}×{o.shape[1]}',ck('FN1'),ck('ALDH2')])
pd.DataFrame(rows,columns=['데이터','새','기존','FN1','ALDH2'])

         데이터         새        기존 FN1 ALDH2
0   GSE30529  13041×22  13041×22   O     O
1   GSE96804  23910×61  33720×61   O     O
2  GSE104948  12042×33  12042×33   O     O
3  GSE104954  12042×38  12042×38   O     O
4  GSE142025  17184×36  17184×36   O     O

## 논문(Table S1) 대조 — 샘플 수

※ 논문 S1은 **샘플 수만** 제공 (유전자 수는 없음).
→ 샘플 수로 대조. (유전자 수는 논문에 없어 대조 불가)

In [14]:
import pandas as pd, os
from collections import Counter
B='../01_preprocessing/bulk/output'; 
paper={'GSE96804':'DKD 41 / Ctrl 20','GSE104948':'DKD 12 / Ctrl 21','GSE104954':'DKD 17 / Ctrl 21',
       'GSE142025':'Early 6 / Late 21 / Ctrl 9','GSE30529':'DKD 10 / Ctrl 12'}
rows=[]
for g in ['GSE96804','GSE104948','GSE104954','GSE142025','GSE30529']:
    df=pd.read_csv(f'{B}/02_normalized/{g}.normalized.txt',sep='\t',index_col=0)
    c=Counter(x.split('_')[-1] for x in df.columns)
    ours=' / '.join(f'{k} {v}' for k,v in c.items())
    match='일치' if sum(c.values())==sum(int(x.split()[1]) for x in paper[g].split(' / ')) else '확인'
    rows.append([g, paper[g], ours, match, f'{df.shape[0]} (논문 N/A)'])
pd.DataFrame(rows,columns=['데이터','논문 샘플(S1)','우리 샘플','샘플수 일치','전처리후 유전자'])

,데이터,논문 샘플(S1),우리 샘플,샘플수 일치,전처리후 유전자
0,GSE96804,DKD 41 / Ctrl 20,DKD 41 / Control 20,일치,23910 (논문 N/A)
1,GSE104948,DKD 12 / Ctrl 21,DKD 12 / Control 21,일치,12042 (논문 N/A)
2,GSE104954,DKD 17 / Ctrl 21,DKD 17 / Control 21,일치,12042 (논문 N/A)
3,GSE142025,Early 6 / Late 21 / Ctrl 9,Late 21 / Early 6 / Control 9,일치,17184 (논문 N/A)
4,GSE30529,DKD 10 / Ctrl 12,DKD 10 / Control 12,일치,13041 (논문 N/A)